version: "3"
services:
  test-suites:
    image: yassmahf98/selenium:latest
    environment:
      - HUB_HOST=hub
      - BROWSER
      - THREAD_COUNT=1
      - TEST_SUITE
    volumes:
      - ${TEST_OUTPUT_VOLUME}:/home/selenium-docker/test-output
